### PR TITLE
Handle empty calendar title, solved issue #163

### PR DESCRIPTION
**Pull request by nativix**

### CODE REVIEW

**Comment by saghul** [comment]
@nativix Nice find! There is another occurrence of this:

~~~
diff --git a/RNCalendarEvents.m b/RNCalendarEvents.m
index ad9f009..dea6567 100644
--- a/RNCalendarEvents.m
+++ b/RNCalendarEvents.m
@@ -473,7 +473,7 @@ - (NSDictionary *)serializeCalendarEvent:(EKEvent *)event
     if (event.calendar) {
         [formedCalendarEvent setValue:@{
                                         @"id": event.calendar.calendarIdentifier,
-                                        @"title": event.calendar.title,
+                                        @"title": event.calendar.title ? event.calendar.title : @"",
                                         @"source": event.calendar.source.title,
                                         @"allowsModifications": @(event.calendar.allowsContentModifications),
                                         @"allowedAvailabilities": [self calendarSupportedAvailabilitiesFromMask:event.calendar.supportedEventAvailabilities],

~~~

**Comment by wmcmahan** [comment]
Thanks @nativix !

**Comment by saghul** [comment]
@wmcmahan can you please apply the fix I posted there too? Otherwise the issue still exists.

**Comment by wmcmahan** [comment]
@saghul, yes i will push a fix for this soon.

**Pull request merged**
