### PR TITLE
Add TypeScript definitions 📝

### PR DESCRIPTION
**Pull request by aarkalyk**
Hey 👋🏽

Small PR to add Typescript definitions ✨

### CODE REVIEW

**Comment by wmcmahan** [comment]
Cool! Thanks @aarkalyk

**Comment by aarkalyk** [comment]
@wmcmahan Thanks for merging! Can you please publish a new version of the package?

**Comment by wmcmahan** [comment]
@aarkalyk There are other changes needed. I will publish when everything is set.

**Comment by bramski** [comment]
Did this ever get published?

**Comment by MoOx** [comment]
Did you ever tried to upgrade or looks at the package en npm?

**Comment by bramski** [comment]
The file appears to be there, `src/index.d.ts` but it's ineffective at least in my IDE (Webstorm). So something seems wrong with how it's being referenced I would guess. This is version `2.1.0`

**Comment by wmcmahan** [comment]
@bramski Sorry, looks like with some directory changes in V2 the TS declarations moved from the root of the project and fell out of reference. This should correct it: #328

**Pull request merged**
