### PR TITLE
add ability to set timezone on events in iOS. necessary for recurrenc…

### PR DESCRIPTION
**Pull request by mcarlson**
…e expansion to work correctly across daylight savings time transitions

### CODE REVIEW

**Comment by MoOx** [comment]
Hi @mcarlson, could you add some documentation? And maybe adjust index.d.ts for the signature? Thank you!

**Comment by mcarlson** [comment]
I added some documentation. Let me know what else you need, thank you!

**Comment by wmcmahan** [comment]
Thanks @mcarlson!

**Review by MoOx — COMMENTED** [review]
Just a small change and a minor issue in TS definition but I will fix that on master :) 
Thanks for this!

**Comment by MoOx** [comment]
Available in 2.2.0, thanks again!

**Pull request merged**
