### PR TITLE
Initia Android support

### PR DESCRIPTION
**Pull request by lilach**

### CODE REVIEW

**Comment by lilach** [comment]
@tomerlevi444 @rauchy

**Comment by tomerlevi444** [comment]
Approved

**Comment by wmcmahan** [comment]
@lilach Thanks, for the help on the Android side. Could you rebase these changes off the current master branch?

**Comment by lilach** [comment]
@wmcmahan rebased :)

**Comment by wmcmahan** [comment]
Thanks @lilach!

**Comment by gilesvangruisen** [comment]
Thanks for this @lilach. Unfortunately I'm seeing a native error when I make a call to `RNCalendarEvents.saveEvent` on Android.

Here's that stack trace in case it helps: 

```
Error: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference
    at createErrorFromErrorData (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7099:11)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7062:35
    at MessageQueue.__invokeCallback (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7442:10)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7294:8
    at guard (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7213:1)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7293:1)
    at onmessage (http://localhost:8081/debuggerWorker.js:44:56)
```

**Pull request merged**
