### PR TITLE
Update RNCalendarEvents.m

### PR DESCRIPTION
**Pull request by eladgel**
Dont add structured location if no title and no radius, the app crashes otherwise

### CODE REVIEW

**Comment by mtimmens** [comment]
Thanks, this resolved #258 for us.

**Comment by saghul** [comment]
@wmcmahan Any chance you could merge this one?

**Comment by robertherber** [comment]
Please merge this, spent A LOT of time tracking down this bug. Thanks!

**Comment by eladgel** [comment]
Also added a check to make sure a calendar event has a color otherwise the app crashes

**Comment by prasanthsd** [comment]
Can we please have this merged?

**Comment by alindao-charles** [comment]
Any updates on this?

**Comment by MoOx** [comment]
This has been merged. Just not released yet as I didn't have the time to test the integrity of the recent merged work.
If you want to help, you can try to use master branch & check if everything run correctly!

**Pull request merged**
