### PR TITLE
Improve iOS calendar source detection

### PR DESCRIPTION
**Pull request by filipef101**
And fallback to default, and potentially to an exchange calendar.

### CODE REVIEW

**Comment by filipef101** [comment]
@wmcmahan This was created because the iCloud (or any potential calendar source) wasn't found. Possible reasons can be as simple as renaming iCloud calendar so something other than "iCloud".

**Comment by filipef101** [comment]
@MoOx This fixes https://github.com/wmcmahan/react-native-calendar-events/issues/285

**Comment by filipef101** [comment]
Actually changed to just icloud or local because there's no guarantee we can create new calendars in any caldav source. ex, we can't on gmail. But supporting EKSourceTypeSubscribed with local fixes the scenario where if you don't have icloud but have some caldav would simply return that you have no sources.

**Comment by filipef101** [comment]
Actually changed to just icloud or local because there's no guarantee we can create new calendars in any caldav source. ex, we can't on gmail. But supporting EKSourceTypeSubscribed with local fixes the scenario where if you don't have icloud but have some caldav would simply return that you have no sources.

**Comment by MoOx** [comment]
I will trust you on this :)

**Pull request merged**
